
server:
  port: 8083
  servlet:
    context-path: /e-signature


spring:
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:e-signature-db
  #    url: jdbc:h2:file:./H2_DB/hazelcast-client-server-db
  freemarker:
    enabled=true:
    template-loader-path: classpath:/templates
    suffix: .ftl
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      springframework: info

