
server:
  port: 8083
  servlet:
    context-path: /e-signature

spring:
  main:
    banner-mode: "off"
  jpa:
    ### h2 db config ##
#    database: h2
#    hibernate:
#      dialect: org.hibernate.dialect.H2Dialect
#      ddl-auto: create-drop


    ### postgreSql db config ##
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
#      hbm2ddl:   # this attribute not resolved#
#        import_files: import.sql   # this attribute not resolved#

  ##      database: postgresql
##      open-in-view: false
##      ddl-auto: create-drop


  datasource:
    ### h2 db config ##
#    url: jdbc:h2:mem:e-signature-db
##    url: jdbc:h2:file:./H2_DB/hazelcast-client-server-db


  ### postgreSql db config ##
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    data-username: postgres
    data-password: postgres
    username: postgres
    password: postgres
#    data: import.sql

#    hikari:
#      schema: /schema.sql


  freemarker:
    enabled: true
    template-loader-path: classpath:/templates
    suffix: .ftl
#  h2:
#    console:
#      enabled: true
#      path: /h2

logging:
  level:
    org:
      springframework: info

